name: arber
description: Arb Excel translator

publish_to: 'none'

version: 1.2.3+19

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  rive: 0.13.20

  file_picker: ^10.3.10
  excel:
    git:
      url: https://github.com/justkawal/excel
      ref: 37e0807f97fe8c293bdf75441cf21413b322882d
  computer: ^3.2.1

  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4

  dio: ^5.9.1

  window_manager: ^0.5.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.11.1
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    image: true
    rive: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/